server:
  port: 8081
  servlet:
    context-path: /api/v1.0/moviebooking

  spring:
    application:
      name: movie-booking-service
    mvc:
      static-path-pattern: "/**"
    web:
      resources:
        add-mappings: false


  data:
    mongodb:
      uri: mongodb://localhost:27017/moviebooking_db  #data base name, to start mongod , ctrl+c

    jackson:
      serialization:
        indent-output: true

    info:
      app:
        name: Movie Booking App
        version: 1.0.0
        description: Full-st

logging:
    level:
        root: INFO
        org.springframework.web: DEBUG
        com.moviebooking.movie_booking_service: DEBUG